### ISSUE TITLE
Iron man helmets in Background

### ISSUE THREAD

**Issue by hvb24** [Lakshit-Chiranjiv/Ironman-Snap#7]
I wanna put helmets in background and wanna give background .
Can i do it?
@Lakshit-Chiranjiv

**Comment by Lakshit-Chiranjiv** [comment]
Could you please explain your ideas a bit more , I'm not exactly getting it.

**Comment by hvb24** [comment]
I will arrange Mark-1, Mark -2,Mark-3, and Mark-42 helmets floating beside the iron man.
@Lakshit-Chiranjiv

**Comment by Lakshit-Chiranjiv** [comment]
Go ahead,but it'll be merged only if its suitable so make sure it looks good.
Also go through the readme and follow the steps while making contibutions.
All the best...

**Comment by hvb24** [comment]
Do you like it? @Lakshit-Chiranjiv 
![image](https://user-images.githubusercontent.com/79647524/138479263-44c68df1-70a1-421e-8d83-955783386181.png)
If you want i can link every helmet to its suit specification link website also.

**Comment by Lakshit-Chiranjiv** [comment]
If you wish you can link them.
Yeah they look good, I will also think about adding animations to the helmets later on.
You can make a pull request for this ,and I will merge it after reviewing your code
